version: '3.5'

services:
  inzdb:
    container_name: inzdb
    image: postgres:12.2
    restart: on-failure
    env_file:
      - 'inz_backend_docker.env'
    environment:
      PORT: 5432
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data/content:/var/lib/postgresql/data
