version: '3.5'

services:
  inzdb:
    container_name: inzdb
    image: postgres:12.2
    restart: on-failure
    env_file:
      - 'inz_backend_docker.env'
    environment:
      PORT: 5432
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data/content:/var/lib/postgresql/data
      - ./dbscripts/:/docker-entrypoint-initdb.d/
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - '15672:15672'
      - '5672:5672'
  cache:
    container_name: cache
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./cache:/redis_data

