version: 2.1

jobs:
  test:
    docker:
      - image: cimg/openjdk:11.0
    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}
            - v1-dependencies-

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}

      - run:
          name: Test whole app
          command: ./gradlew test

  build-deploy-dev:
    parameters:
      envs:
        description: project environments
        default: "ecsb-moving"
        type: string
    docker:
      - image: cimg/openjdk:11.0
    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}
            - v1-dependencies-

      - run:
          name: Create jars for all projects
          command: |
            printf "Creating Jars for projects in backend\n"
            mkdir /tmp/build-jars
            for i in <<parameters.envs>>; do
              echo "build: $i"
              echo "$i:buildFatJar"
              ./gradlew clean && ./gradlew $i:buildFatJar
              cp ./$i/build/libs/$i-all.jar /tmp/build-jars/dev-$i-all.jar
            done
      - add_ssh_keys
      - run:
          name: scp to dev
          command: |
            echo "Start scp to dev"
            ssh-keyscan -H ${DEV_HOST} >> ~/.ssh/known_hosts
            for i in <<parameters.envs>>; do
              echo "build: $i"
              echo "$i:buildFatJar"
              scp -r /tmp/build-jars/ ${PROD_USER}@${DEV_HOST}:/home/${PROD_USER}/
            done

  build-deploy-prod:
    parameters:
      envs:
        description: project environments
        default: "ecsb-moving"
        type: string
    docker:
      - image: cimg/openjdk:11.0
    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}
            - v1-dependencies-

      - run:
          name: Create jars for all projects
          command: |
            printf "Creating Jars for projects in backend\n"
            mkdir /tmp/build-jars
            for i in <<parameters.envs>>; do
              echo "build: $i"
              echo "$i:buildFatJar"
              ./gradlew clean && ./gradlew $i:buildFatJar
              cp ./$i/build/libs/$i-all.jar /tmp/build-jars/prod-$i-all.jar
            done
      - add_ssh_keys
      - run:
          name: scp to prod
          command: |
            echo "Start scp to prod"
            ssh-keyscan -H ${DEV_HOST} >> ~/.ssh/known_hosts
            for i in <<parameters.envs>>; do
              echo "build: $i"
              echo "$i:buildFatJar"
              scp -r /tmp/build-jars/ ${PROD_USER}@${DEV_HOST}:/home/${PROD_USER}/
            done
workflows:
  only-test:
    jobs:
      - test
    when:
      and:
        - not:
            equal: [master, << pipeline.git.branch >>]
        - not:
            equal: [dev, << pipeline.git.branch >>]
  build-test-deploy-prod:
    jobs:
      - test
      - build-deploy-prod:
          matrix:
            parameters:
              envs: ['ecsb-moving', "ecsb-chat", "ecsb-game-init", "ecsb-game-engine", "ecsb-anal", "ecsb-timer"]
          requires:
            - test
    when:
        equal: [master, << pipeline.git.branch >>]
  build-test-deploy-dev:
    jobs:
      - test
      - build-deploy-dev:
          matrix:
            parameters:
              envs: ['ecsb-moving', "ecsb-chat", "ecsb-game-init", "ecsb-game-engine", "ecsb-anal", "ecsb-timer"]
          requires:
            - test
    when:
        equal: [dev, << pipeline.git.branch >>]

